services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    command: sleep infinity

    networks:
      - pixelart-devcontainer

    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: unless-stopped
    volumes:
      - pixelart-devcontainer-db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    networks:
      - pixelart-devcontainer


volumes:
  pixelart-devcontainer-db:

networks:
  pixelart-devcontainer:
    driver: bridge
