volumes:
  mariadb-prod-data:

name: pixelart

services:
  db:
    image: mariadb:10.6
    restart: always
    networks:
      - app-network
    volumes:
      - mariadb-prod-data:/var/lib/mysql

    env_file:
      - ../environment/.env.dev
      - ../environment/.env.local

  api:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.prod
      target: api-runtime
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

    env_file:
      - ../environment/.env.dev
      - ../environment/.env.local

    environment:
      PORT: ${PORT:-3000}

  landing:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.prod
      target: landing-runtime
    restart: always
    depends_on:
      - api
    networks:
      - app-network

    env_file:
      - ../environment/.env.dev
      - ../environment/.env.local

    environment:
      PORT: ${PORT:-4000}

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../.nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../.nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - landing
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
